;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun in_range ((x Int)) Bool (and (<= 0 x) (<= x 2)))

(define-fun dynamic_invariant ((temp___expr_171 Int)
  (temp___is_init_168 Bool) (temp___skip_constant_169 Bool)
  (temp___do_toplevel_170 Bool)) Bool (=>
                                      (or (= temp___is_init_168 true)
                                      (<= 0 2)) (in_range temp___expr_171)))

(declare-fun c () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(declare-fun p__ident__2__result () Int)

(declare-fun o () Int)

(declare-fun o1 () Int)

(declare-fun o2 () Int)

(declare-fun o3 () Int)

(declare-fun result () Int)

(declare-fun p__ident__2__result1 () Int)

(declare-fun p__ident__2__result2 () Int)

(declare-fun p__ident__2__result3 () Int)

(declare-fun p__ident__2__result4 () Int)

(declare-fun p__ident__2__result5 () Int)

;; H
  (assert (in_range c))

;; H
  (assert (not (= c 2)))

(assert
;; WP_parameter_def
 ;; File "p.adb", line 2, characters 0-0
  (not (not (= c 2))))
(check-sat)
(exit)
