;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun uint_in_range ((i Int)) Bool (and (<= 0 i) (<= i 255)))

(declare-fun abstr () (_ BitVec 8))

(declare-fun abstr1 () (_ BitVec 8))

(declare-fun abstr2 () (_ BitVec 8))

(declare-fun abstr3 () (_ BitVec 8))

(declare-fun abstr4 () (_ BitVec 8))

(define-fun nth_bv ((x (_ BitVec 8))
  (i (_ BitVec 8))) Bool (ite (not (= (bvand (bvlshr x i) #x01) #x00)) true
                         false))

(declare-fun abstr5 () Bool)

(define-fun eq_sub ((a (_ BitVec 8)) (b (_ BitVec 8)) (i Int)
  (n Int)) Bool abstr5)

(define-fun bv_min ((x (_ BitVec 8))
  (y (_ BitVec 8))) (_ BitVec 8) (ite (bvule x y) x y))

(define-fun bv_max ((x (_ BitVec 8))
  (y (_ BitVec 8))) (_ BitVec 8) (ite (bvule x y) y x))

(define-fun to_int1 ((b Bool)) Int (ite (= b true) 1 0))

(define-fun of_int ((i Int)) Bool (ite (= i 0) false true))

(define-fun in_range ((x Int)) Bool (or (= x 0) (= x 1)))

(declare-fun attr__ATTRIBUTE_MODULUS () (_ BitVec 8))

(declare-fun abstr6 () (_ BitVec 8))

(declare-fun abstr7 () (_ BitVec 8))

(define-fun in_range1 ((x (_ BitVec 8))) Bool (and (bvule abstr7 x)
                                              (bvule x abstr6)))

(define-fun in_range_int ((x Int)) Bool (and (<= 0 x) (<= x 10)))

(define-fun dynamic_invariant ((temp___expr_202 (_ BitVec 8))
  (temp___is_init_199 Bool) (temp___skip_constant_200 Bool)
  (temp___do_toplevel_201 Bool)) Bool (=>
                                      (or (= temp___is_init_199 true)
                                      (bvule abstr7 abstr6)) (in_range1
                                      temp___expr_202)))

(declare-fun attr__ATTRIBUTE_MODULUS1 () (_ BitVec 8))

(declare-fun abstr8 () (_ BitVec 8))

(define-fun in_range2 ((x (_ BitVec 8))) Bool (and (bvule abstr8 x)
                                              (bvule x abstr6)))

(define-fun in_range_int1 ((x Int)) Bool (and (<= 1 x) (<= x 10)))

(declare-fun abstr9 () Bool)

(define-fun bool_eq ((a (Array (_ BitVec 8) Bool)) (a__first (_ BitVec 8))
  (a__last (_ BitVec 8)) (b (Array (_ BitVec 8) Bool))
  (b__first (_ BitVec 8))
  (b__last (_ BitVec 8))) Bool (ite (and
                                    (ite (bvule a__first a__last)
                                    (and (bvule b__first b__last)
                                    (= (bvsub a__last a__first) (bvsub b__last b__first)))
                                    (bvugt b__first b__last)) abstr9)
                               true false))

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS1 () Int)

(define-fun dynamic_invariant1 ((temp___expr_208 (_ BitVec 8))
  (temp___is_init_205 Bool) (temp___skip_constant_206 Bool)
  (temp___do_toplevel_207 Bool)) Bool (=>
                                      (or (= temp___is_init_205 true)
                                      (bvule abstr8 abstr6)) (in_range2
                                      temp___expr_208)))

(declare-fun inputs () (Array (_ BitVec 8) Bool))

(declare-fun res () (_ BitVec 8))

(declare-fun counter__model__current_chain_length__result () (_ BitVec 8))

(declare-fun o () (_ BitVec 8))

(declare-fun temp___228 () (_ BitVec 8))

(declare-fun temp___229 () (_ BitVec 8))

(declare-fun i () (_ BitVec 8))

(declare-fun o1 () (_ BitVec 8))

(declare-fun o2 () (_ BitVec 8))

(declare-fun o3 () Bool)

(declare-fun i1 () (_ BitVec 8))

(declare-fun result () (_ BitVec 8))

(declare-fun res1 () (_ BitVec 8))

(declare-fun result1 () Bool)

(declare-fun res2 () (_ BitVec 8))

(declare-fun temp___2291 () (_ BitVec 8))

(declare-fun result2 () (_ BitVec 8))

(declare-fun temp___2292 () (_ BitVec 8))

(declare-fun result3 () (_ BitVec 8))

(declare-fun res3 () (_ BitVec 8))

(declare-fun result4 () Bool)

(declare-fun res4 () (_ BitVec 8))

(declare-fun temp___2293 () (_ BitVec 8))

(declare-fun res5 () (_ BitVec 8))

(declare-fun temp___2294 () (_ BitVec 8))

(declare-fun res6 () (_ BitVec 8))

(declare-fun res7 () (_ BitVec 8))

(declare-fun res8 () (_ BitVec 8))

(declare-fun res9 () (_ BitVec 8))

(declare-fun result5 () (_ BitVec 8))

(declare-fun counter__model__current_chain_length__result1 () (_ BitVec 8))

(declare-fun counter__model__current_chain_length__result2 () (_ BitVec 8))

(declare-fun counter__model__current_chain_length__result3 () (_ BitVec 8))

(declare-fun res10 () (_ BitVec 8))

(declare-fun counter__model__current_chain_length__result4 () (_ BitVec 8))

(declare-fun res11 () (_ BitVec 8))

(declare-fun counter__model__current_chain_length__result5 () (_ BitVec 8))

(declare-fun result6 () Bool)

;; H
  (assert (= res1 abstr7))

;; H
  (assert (in_range1 res1))

;; H
  (assert (bvult res1 abstr6))

(assert
;; WP_parameter_def
 ;; File "counter.ads", line 9, characters 0-0
  (not (bvule abstr8 (bvsub abstr6 res1))))
(check-sat)
(exit)
