;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun mod1 ((x Int)
  (y Int)) Int (ite (< 0 y) (mod x y) (+ (mod x y) y)))

(define-fun to_int1 ((b Bool)) Int (ite (= b true) 1 0))

(define-fun of_int ((i Int)) Bool (ite (= i 0) false true))

(define-fun in_range ((x Int)) Bool (or (= x 0) (= x 1)))

(define-fun in_range1 ((x Int)) Bool (and (<= (- 2147483648) x)
                                     (<= x 2147483647)))

(define-fun in_range2 ((x Int)) Bool (and (<= (- 2147483648) x)
                                     (<= x 2147483647)))

(define-fun dynamic_invariant ((temp___expr_159 Int)
  (temp___is_init_156 Bool) (temp___skip_constant_157 Bool)
  (temp___do_toplevel_158 Bool)) Bool (=>
                                      (or (= temp___is_init_156 true)
                                      (<= (- 2147483648) 2147483647))
                                      (in_range2 temp___expr_159)))

(declare-fun left () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(declare-fun right () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS1 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS2 () Int)

(declare-fun quotient () Int)

(declare-fun o () Int)

(declare-fun o1 () Int)

(declare-fun o2 () Int)

(declare-fun o3 () Int)

(declare-fun o4 () Int)

(declare-fun o5 () Int)

(declare-fun o6 () Int)

(declare-fun o7 () Int)

(declare-fun o8 () Int)

(declare-fun o9 () Int)

(declare-fun o10 () Int)

(declare-fun o11 () Int)

(declare-fun o12 () Int)

(declare-fun o13 () Int)

(declare-fun o14 () Int)

(declare-fun o15 () Int)

(declare-fun o16 () Int)

(declare-fun result () Int)

(declare-fun quotient1 () Int)

;; H
  (assert (in_range2 left))

;; H
  (assert (in_range2 right))

;; H
  (assert (not (= right 0)))

;; H
  (assert (=> (< left 0) (=> (< left 0) (not (< right 0)))))

;; H
  (assert (=> (not (< left 0)) (< right 0)))

;; H
  (assert (=> (not (< left 0)) (=> (< left 0) (not (< right 0)))))

;; H
  (assert (and (= o1 (abs right)) (in_range1 (abs right))))

;; H
  (assert (and (= o (abs left)) (in_range1 (abs left))))

(declare-fun abstr () Int)

;; H
  (assert (= o2 abstr))

;; H
  (assert (and (= o3 o2) (in_range1 o2)))

(assert
;; WP_parameter_def
 ;; File "interfac.ads", line 52, characters 0-0
  (not (in_range2 o3)))
(check-sat)
(exit)
