;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun in_range ((x Int)) Bool (and (<= (- 2147483648) x)
                                    (<= x 2147483647)))

(define-fun dynamic_invariant ((temp___expr_15 Int) (temp___is_init_12 Bool)
  (temp___skip_constant_13 Bool)
  (temp___do_toplevel_14 Bool)) Bool (=>
                                     (or (= temp___is_init_12 true)
                                     (<= (- 2147483648) 2147483647))
                                     (in_range temp___expr_15)))

(declare-fun item () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(declare-fun basic_contracts__increment__result () Int)

(declare-fun o () Int)

(declare-fun o1 () Int)

(declare-fun result () Int)

(declare-fun basic_contracts__increment__result1 () Int)

(declare-fun basic_contracts__increment__result2 () Int)

(declare-fun basic_contracts__increment__result3 () Int)

(declare-fun basic_contracts__increment__result4 () Int)

(declare-fun basic_contracts__increment__result5 () Int)

(declare-fun result1 () Int)

;; H
  (assert (in_range item))

;; H
  (assert (< item 2147483647))

;; H
  (assert
  (= basic_contracts__increment__result1 basic_contracts__increment__result2))

;; H
  (assert
  (= basic_contracts__increment__result3 basic_contracts__increment__result1))

;; H
  (assert (and (= o (+ item 1)) (in_range (+ item 1))))

;; H
  (assert (= basic_contracts__increment__result1 o))

;; H
  (assert
  (= basic_contracts__increment__result5 basic_contracts__increment__result3))

;; H
  (assert (= result1 basic_contracts__increment__result4))

(assert
;; WP_parameter_def
 ;; File "system.ads", line 1, characters 0-0
  (not (= basic_contracts__increment__result4 (+ item 1))))
(check-sat)
(exit)
