;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun mod1 ((x Int)
  (y Int)) Int (ite (< 0 y) (mod x y) (+ (mod x y) y)))

(define-fun to_int1 ((b Bool)) Int (ite (= b true) 1 0))

(define-fun of_int ((i Int)) Bool (ite (= i 0) false true))

(define-fun in_range ((x Int)) Bool (or (= x 0) (= x 1)))

(define-fun in_range1 ((x Int)) Bool (and (<= 2000 x) (<= x 2099)))

(define-fun dynamic_invariant ((temp___expr_150 Int)
  (temp___is_init_147 Bool) (temp___skip_constant_148 Bool)
  (temp___do_toplevel_149 Bool)) Bool (=>
                                      (or (= temp___is_init_147 true)
                                      (<= 2000 2099)) (in_range1
                                      temp___expr_150)))

(define-fun in_range2 ((x Int)) Bool (and (<= 1 x) (<= x 12)))

(define-fun dynamic_invariant1 ((temp___expr_156 Int)
  (temp___is_init_153 Bool) (temp___skip_constant_154 Bool)
  (temp___do_toplevel_155 Bool)) Bool (=>
                                      (or (= temp___is_init_153 true)
                                      (<= 1 12)) (in_range2 temp___expr_156)))

(define-fun in_range3 ((x Int)) Bool (and (<= 1 x) (<= x 31)))

(define-fun dynamic_invariant2 ((temp___expr_162 Int)
  (temp___is_init_159 Bool) (temp___skip_constant_160 Bool)
  (temp___do_toplevel_161 Bool)) Bool (=>
                                      (or (= temp___is_init_159 true)
                                      (<= 1 31)) (in_range3 temp___expr_162)))

(declare-fun year () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(declare-fun month () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS1 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS2 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS3 () Int)

(declare-fun c8b () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS4 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS5 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS6 () Int)

(declare-fun length () Int)

(declare-fun c9b () Bool)

(declare-fun result__ () Bool)

(declare-fun dates__get_month_length__result () Int)

(declare-fun result () Bool)

(declare-fun result__1 () Bool)

(declare-fun result1 () Bool)

(declare-fun result__2 () Bool)

(declare-fun result2 () Bool)

(declare-fun c9b1 () Bool)

(declare-fun result3 () Int)

(declare-fun length1 () Int)

(declare-fun result4 () Int)

(declare-fun length2 () Int)

(declare-fun result5 () Int)

(declare-fun dates__get_month_length__result1 () Int)

(declare-fun dates__get_month_length__result2 () Int)

(declare-fun dates__get_month_length__result3 () Int)

(declare-fun length3 () Int)

(declare-fun c9b2 () Bool)

(declare-fun result__3 () Bool)

(declare-fun dates__get_month_length__result4 () Int)

(declare-fun length4 () Int)

(declare-fun c9b3 () Bool)

(declare-fun result__4 () Bool)

(declare-fun dates__get_month_length__result5 () Int)

;; H
  (assert (in_range1 year))

;; H
  (assert (in_range2 month))

;; H
  (assert (=> (<= 1 31) (in_range3 length)))

;; H
  (assert (= year c8b))

;; H
  (assert (in_range1 c8b))

;; H
  (assert (= result__1 (of_int 0)))

(assert
;; WP_parameter_def
 ;; File "dates.ads", line 6, characters 0-0
  (not (not (= 4 0))))
(check-sat)
(exit)
