;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun to_int1 ((b Bool)) Int (ite (= b true) 1 0))

(define-fun of_int ((i Int)) Bool (ite (= i 0) false true))

(define-fun in_range ((x Int)) Bool (or (= x 0) (= x 1)))

(define-fun in_range1 ((x Int)) Bool (and (<= (- 2147483648) x)
                                     (<= x 2147483647)))

(define-fun in_range2 ((x Int)) Bool (and (<= 1 x) (<= x 2147483647)))

(define-fun dynamic_invariant ((temp___expr_39 Int) (temp___is_init_36 Bool)
  (temp___skip_constant_37 Bool)
  (temp___do_toplevel_38 Bool)) Bool (=>
                                     (or (= temp___is_init_36 true)
                                     (<= 1 2147483647)) (in_range2
                                     temp___expr_39)))

(define-fun dynamic_property ((range_first Int) (range_last Int) (low Int)
  (high Int)) Bool (and (in_range1 low)
                   (and (in_range1 high)
                   (=> (<= low high) (and (in_range2 low) (in_range2 high))))))

(declare-fun value__size () Int)

(declare-fun value__component__size () Int)

(declare-fun value__alignment () Int)

;; value__size_axiom
  (assert (<= 0 value__size))

;; value__component__size_axiom
  (assert (<= 0 value__component__size))

;; value__alignment_axiom
  (assert (<= 0 value__alignment))

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(define-fun dynamic_property1 ((first_int Int) (last_int Int)
  (x Int)) Bool (and (<= first_int x) (<= x last_int)))

(define-fun dynamic_property2 ((range_first Int) (range_last Int) (low Int)
  (high Int)) Bool (and (in_range1 low)
                   (and (in_range1 high)
                   (=> (<= low high)
                   (and (dynamic_property1 range_first range_last low)
                   (dynamic_property1 range_first range_last high))))))

(declare-fun value__size1 () Int)

(declare-fun value__component__size1 () Int)

(declare-fun value__alignment1 () Int)

;; value__size_axiom
  (assert (<= 0 value__size1))

;; value__component__size_axiom
  (assert (<= 0 value__component__size1))

;; value__alignment_axiom
  (assert (<= 0 value__alignment1))

(declare-fun attr__ATTRIBUTE_ADDRESS1 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS2 () Int)

(define-fun dynamic_property3 ((first_int Int) (last_int Int)
  (x Int)) Bool (and (<= first_int x) (<= x last_int)))

(declare-fun attr__ATTRIBUTE_ADDRESS3 () Int)

(define-fun dynamic_property4 ((first_int Int) (last_int Int)
  (x Int)) Bool (and (<= first_int x) (<= x last_int)))

(define-fun dynamic_property5 ((range_first Int) (range_last Int) (low Int)
  (high Int)) Bool (and (in_range1 low)
                   (and (in_range1 high)
                   (=> (<= low high)
                   (and (dynamic_property4 range_first range_last low)
                   (dynamic_property4 range_first range_last high))))))

(declare-fun value__size2 () Int)

(declare-fun value__component__size2 () Int)

(declare-fun value__alignment2 () Int)

;; value__size_axiom
  (assert (<= 0 value__size2))

;; value__component__size_axiom
  (assert (<= 0 value__component__size2))

;; value__alignment_axiom
  (assert (<= 0 value__alignment2))

(define-fun dynamic_invariant1 ((temp___expr_15 Int) (temp___is_init_12 Bool)
  (temp___skip_constant_13 Bool)
  (temp___do_toplevel_14 Bool)) Bool (=>
                                     (or (= temp___is_init_12 true)
                                     (<= (- 2147483648) 2147483647))
                                     (in_range1 temp___expr_15)))

(declare-fun smallest () Int)

(declare-fun current () Int)

(declare-fun temp___202 () Int)

(declare-fun temp___196 () Int)

(declare-fun temp___195 () Int)

(declare-fun o () Int)

(declare-fun o1 () Int)

(declare-fun j () Int)

(declare-fun o2 () Int)

(declare-fun o3 () Int)

(declare-fun j1 () Int)

(declare-fun temp___200 () Int)

(declare-fun o4 () Int)

(declare-fun o5 () Int)

(declare-fun o6 () Int)

(declare-fun o7 () Int)

(declare-fun j2 () Int)

(declare-fun o8 () Int)

(declare-fun o9 () Bool)

(declare-fun temp___205 () Int)

(declare-fun o10 () Int)

(declare-fun o11 () Int)

(declare-fun smallest1 () Int)

(declare-fun result () Int)

(declare-fun current1 () Int)

(declare-fun result1 () Int)

(declare-fun smallest2 () Int)

(declare-fun smallest3 () Int)

(declare-fun current2 () Int)

(declare-fun result2 () Int)

(declare-fun current3 () Int)

(declare-fun result3 () Int)

(declare-fun smallest4 () Int)

(declare-fun smallest5 () Int)

(declare-fun current4 () Int)

(declare-fun smallest6 () Int)

(declare-fun current5 () Int)

(declare-fun smallest7 () Int)

(declare-fun current6 () Int)

(declare-fun result4 () Bool)

;; H
  (assert (=> (<= 1 2147483647) (in_range2 smallest)))

;; H
  (assert (<= current1 temp___202))

;; H
  (assert true)

;; H
  (assert (= smallest2 o))

;; H
  (assert
  (=> (not (= smallest2 current1))
  (and (= o1 current1) (in_range2 current1))))

;; H
  (assert (<= j1 current2))

;; H
  (assert (and (= temp___200 (+ j1 1)) (in_range1 (+ j1 1))))

(assert
;; WP_parameter_def
 ;; File "sorters.ads", line 7, characters 0-0
  (not false))
(check-sat)
(exit)
