;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun in_range ((x Int)) Bool (and (<= 0 x) (<= x 2147483647)))

(define-fun in_range1 ((x Int)) Bool (and (<= 1 x) (<= x 2147483647)))

(define-fun in_range2 ((x Int)) Bool (and (<= (- 2147483648) x)
                                     (<= x 2147483647)))

(define-fun in_range3 ((x Int)) Bool (and (<= (- 2147483648) x)
                                     (<= x 2147483647)))

(define-fun dynamic_property ((first_int Int) (last_int Int)
  (x Int)) Bool (and (<= first_int x) (<= x last_int)))

(define-fun dynamic_property1 ((range_first Int) (range_last Int) (low Int)
  (high Int)) Bool (and (in_range2 low)
                   (and (in_range2 high)
                   (=> (<= low high)
                   (and (dynamic_property range_first range_last low)
                   (dynamic_property range_first range_last high))))))

(declare-fun value__size () Int)

(declare-fun value__component__size () Int)

(declare-fun value__alignment () Int)

;; value__size_axiom
  (assert (<= 0 value__size))

;; value__component__size_axiom
  (assert (<= 0 value__component__size))

;; value__alignment_axiom
  (assert (<= 0 value__alignment))

(declare-fun value__size1 () Int)

(declare-fun value__alignment1 () Int)

;; value__size_axiom
  (assert (<= 0 value__size1))

;; value__alignment_axiom
  (assert (<= 0 value__alignment1))

(declare-fun bounded_queue_v1__queue_type__max_size__first__bit () Int)

(declare-fun bounded_queue_v1__queue_type__max_size__last__bit () Int)

(declare-fun bounded_queue_v1__queue_type__max_size__position () Int)

;; bounded_queue_v1__queue_type__max_size__first__bit_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__max_size__first__bit))

;; bounded_queue_v1__queue_type__max_size__last__bit_axiom
  (assert
  (< bounded_queue_v1__queue_type__max_size__first__bit bounded_queue_v1__queue_type__max_size__last__bit))

;; bounded_queue_v1__queue_type__max_size__position_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__max_size__position))

(declare-fun bounded_queue_v1__queue_type__count__first__bit () Int)

(declare-fun bounded_queue_v1__queue_type__count__last__bit () Int)

(declare-fun bounded_queue_v1__queue_type__count__position () Int)

;; bounded_queue_v1__queue_type__count__first__bit_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__count__first__bit))

;; bounded_queue_v1__queue_type__count__last__bit_axiom
  (assert
  (< bounded_queue_v1__queue_type__count__first__bit bounded_queue_v1__queue_type__count__last__bit))

;; bounded_queue_v1__queue_type__count__position_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__count__position))

(declare-fun bounded_queue_v1__queue_type__front__first__bit () Int)

(declare-fun bounded_queue_v1__queue_type__front__last__bit () Int)

(declare-fun bounded_queue_v1__queue_type__front__position () Int)

;; bounded_queue_v1__queue_type__front__first__bit_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__front__first__bit))

;; bounded_queue_v1__queue_type__front__last__bit_axiom
  (assert
  (< bounded_queue_v1__queue_type__front__first__bit bounded_queue_v1__queue_type__front__last__bit))

;; bounded_queue_v1__queue_type__front__position_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__front__position))

(declare-fun bounded_queue_v1__queue_type__rear__first__bit () Int)

(declare-fun bounded_queue_v1__queue_type__rear__last__bit () Int)

(declare-fun bounded_queue_v1__queue_type__rear__position () Int)

;; bounded_queue_v1__queue_type__rear__first__bit_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__rear__first__bit))

;; bounded_queue_v1__queue_type__rear__last__bit_axiom
  (assert
  (< bounded_queue_v1__queue_type__rear__first__bit bounded_queue_v1__queue_type__rear__last__bit))

;; bounded_queue_v1__queue_type__rear__position_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__rear__position))

(declare-fun bounded_queue_v1__queue_type__items__first__bit () Int)

(declare-fun bounded_queue_v1__queue_type__items__last__bit () Int)

(declare-fun bounded_queue_v1__queue_type__items__position () Int)

;; bounded_queue_v1__queue_type__items__first__bit_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__items__first__bit))

;; bounded_queue_v1__queue_type__items__last__bit_axiom
  (assert
  (< bounded_queue_v1__queue_type__items__first__bit bounded_queue_v1__queue_type__items__last__bit))

;; bounded_queue_v1__queue_type__items__position_axiom
  (assert (<= 0 bounded_queue_v1__queue_type__items__position))

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(define-fun dynamic_invariant ((temp___expr_33 Int) (temp___is_init_30 Bool)
  (temp___skip_constant_31 Bool)
  (temp___do_toplevel_32 Bool)) Bool (=>
                                     (or (= temp___is_init_30 true)
                                     (<= 0 2147483647)) (in_range
                                     temp___expr_33)))

(define-fun dynamic_invariant1 ((temp___expr_39 Int) (temp___is_init_36 Bool)
  (temp___skip_constant_37 Bool)
  (temp___do_toplevel_38 Bool)) Bool (=>
                                     (or (= temp___is_init_36 true)
                                     (<= 1 2147483647)) (in_range1
                                     temp___expr_39)))

(define-fun dynamic_invariant2 ((temp___expr_15 Int) (temp___is_init_12 Bool)
  (temp___skip_constant_13 Bool)
  (temp___do_toplevel_14 Bool)) Bool (=>
                                     (or (= temp___is_init_12 true)
                                     (<= (- 2147483648) 2147483647))
                                     (in_range2 temp___expr_15)))

(define-fun dynamic_invariant3 ((temp___expr_146 Int)
  (temp___is_init_143 Bool) (temp___skip_constant_144 Bool)
  (temp___do_toplevel_145 Bool)) Bool (=>
                                      (or (= temp___is_init_143 true)
                                      (<= (- 2147483648) 2147483647))
                                      (in_range3 temp___expr_146)))

(declare-fun us () Int)

(assert
;; WP_parameter_def
 ;; File "bounded_queue_v1.ads", line 17, characters 0-0
  (not false))
(check-sat)
(exit)
