;; produced by colibri_gnatprove.drv ;;
(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(define-fun to_int1 ((b Bool)) Int (ite (= b true) 1 0))

(define-fun of_int ((i Int)) Bool (ite (= i 0) false true))

(define-fun in_range ((x Int)) Bool (or (= x 0) (= x 1)))

(define-fun in_range1 ((x Int)) Bool (and (<= 0 x) (<= x 75)))

(define-fun dynamic_invariant ((temp___expr_136 Int)
  (temp___is_init_133 Bool) (temp___skip_constant_134 Bool)
  (temp___do_toplevel_135 Bool)) Bool (=>
                                      (or (= temp___is_init_133 true)
                                      (<= 0 75)) (in_range1 temp___expr_136)))

(define-fun in_range2 ((x Int)) Bool (and (<= 1 x) (<= x 75)))

(define-fun dynamic_invariant1 ((temp___expr_142 Int)
  (temp___is_init_139 Bool) (temp___skip_constant_140 Bool)
  (temp___do_toplevel_141 Bool)) Bool (=>
                                      (or (= temp___is_init_139 true)
                                      (<= 1 75)) (in_range2 temp___expr_142)))

(define-fun in_range3 ((x Int)) Bool (and (<= 0 x) (<= x 4)))

(define-fun dynamic_invariant2 ((temp___expr_178 Int)
  (temp___is_init_175 Bool) (temp___skip_constant_176 Bool)
  (temp___do_toplevel_177 Bool)) Bool (=>
                                      (or (= temp___is_init_175 true)
                                      (<= 0 4)) (in_range3 temp___expr_178)))

(declare-fun attr__ATTRIBUTE_ADDRESS () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS1 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS2 () Int)

(declare-fun attr__ATTRIBUTE_ADDRESS3 () Int)

(declare-fun letter () Int)

(declare-fun number () Int)

(declare-fun the_count () Int)

(declare-fun o () Int)

(declare-fun o1 () Int)

(declare-fun o2 () Int)

(declare-fun result () Int)

(declare-fun number1 () Int)

;; H
  (assert (in_range1 the_count))

;; H
  (assert (=> (<= 0 4) (in_range3 letter)))

;; H
  (assert (=> (<= 1 75) (in_range2 number)))

(declare-fun abstr () Bool)

;; H
  (assert (not (= abstr true)))

(assert
;; WP_parameter_def
 ;; File "bingo_basket.ads", line 4, characters 0-0
  (not (<= 1 the_count)))
(check-sat)
(exit)
